# Generated by Django 4.2.5 on 2023-12-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoList_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="task",
            field=models.CharField(max_length=125),
        ),
    ]
