# Generated by Django 4.2.5 on 2023-12-15 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todoList_app", "0003_alter_guest_task"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="guest",
            new_name="guests",
        ),
    ]
