# Generated by Django 4.2.5 on 2023-12-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoList_app", "0004_rename_guest_guests"),
    ]

    operations = [
        migrations.CreateModel(
            name="guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="guests",
        ),
    ]
